#!/usr/bin/env python3
"""
Void-MC Configuration Setup Script

Interactive CLI for generating the config.toml configuration file.
"""

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("Error: PyYAML not installed. Please run 'make install-deps' first.")
    sys.exit(1)


def print_header(text):
    """Print a formatted header."""
    print("\n" + "=" * 60)
    print(f"  {text}")
    print("=" * 60)


def print_section(text):
    """Print a formatted section header."""
    print(f"\n--- {text} ---")


def get_input(prompt, default=None):
    """Get user input with optional default value."""
    if default:
        response = input(f"{prompt} [{default}]: ").strip()
        return response if response else default
    else:
        while True:
            response = input(f"{prompt}: ").strip()
            if response:
                return response
            print("This field is required. Please enter a value.")


def get_yes_no(prompt, default=True):
    """Get yes/no input from user."""
    default_str = "Y/n" if default else "y/N"
    while True:
        response = input(f"{prompt} [{default_str}]: ").strip().lower()
        if not response:
            return default
        if response in ['y', 'yes']:
            return True
        if response in ['n', 'no']:
            return False
        print("Please enter 'y' or 'n'")


def load_existing_yaml_mods():
    """Load mod lists from existing YAML files if they exist."""
    client_mods = []
    server_mods = []
    minecraft_version = "1.21.1"
    fabric_loader = "0.18.3"

    client_yaml = Path("client/client-mods.yaml")
    server_yaml = Path("server/server-mods.yaml")

    if client_yaml.exists():
        with open(client_yaml, 'r') as f:
            data = yaml.safe_load(f)
            client_mods = data.get('mods', [])
            if data.get('minecraft', {}).get('version'):
                minecraft_version = data['minecraft']['version']
            if data.get('fabric', {}).get('loader'):
                fabric_loader = data['fabric']['loader']

    if server_yaml.exists():
        with open(server_yaml, 'r') as f:
            data = yaml.safe_load(f)
            server_mods = data.get('mods', [])

    return client_mods, server_mods, minecraft_version, fabric_loader


def generate_toml_content(config):
    """Generate TOML configuration file content."""
    lines = []

    lines.append("# Void-MC Configuration File")
    lines.append("# Generated by setup.py")
    lines.append("#")
    lines.append("# This file contains your Minecraft server configuration.")
    lines.append("# Edit the values below as needed, then run 'make generate-config'")
    lines.append("# to generate the JSON files used by the mod fetcher and server.")
    lines.append("")

    # Minecraft and Fabric versions
    lines.append("[versions]")
    lines.append(f'minecraft = "{config["minecraft_version"]}"')
    lines.append(f'fabric_loader = "{config["fabric_loader"]}"')
    lines.append("")

    # Server settings
    lines.append("[server]")
    lines.append("# Basic server settings")
    lines.append("# Note: Server IP is stored in .env file for security")
    lines.append(f'seed = "{config["seed"]}"')
    lines.append(f'difficulty = "{config["difficulty"]}"')
    lines.append(f'gamemode = "{config["gamemode"]}"')
    lines.append(f'max_players = {config["max_players"]}')
    lines.append(f'view_distance = {config["view_distance"]}')
    lines.append(f'pvp = {str(config["pvp"]).lower()}')
    lines.append(f'online_mode = {str(config["online_mode"]).lower()}')
    lines.append(f'spawn_protection = {config["spawn_protection"]}')
    lines.append("")
    lines.append("# Additional server.properties settings")
    lines.append("# Add any additional server properties below as key-value pairs")
    lines.append("# Example: motd = \"Welcome to my server!\"")
    lines.append(f'motd = "{config["motd"]}"')
    lines.append("")

    # Client mods
    lines.append("[[client_mods]]")
    lines.append("# Client-side mods configuration")
    lines.append("# Each mod should have a 'name' and 'url'")
    lines.append("#")
    if config["client_mods"]:
        lines.append("# Migrated from client-mods.yaml:")
        lines.append("")
        for mod in config["client_mods"]:
            lines.append("[[client_mods.mod]]")
            lines.append(f'name = "{mod["name"]}"')
            lines.append(f'url = "{mod["url"]}"')
            lines.append("")
    else:
        lines.append("# Example:")
        lines.append("# [[client_mods.mod]]")
        lines.append('# name = "sodium"')
        lines.append('# url = "https://cdn.modrinth.com/..."')
        lines.append("")

    # Server mods
    lines.append("[[server_mods]]")
    lines.append("# Server-side mods configuration")
    lines.append("# Each mod should have a 'name' and 'url'")
    lines.append("#")
    if config["server_mods"]:
        lines.append("# Migrated from server-mods.yaml:")
        lines.append("")
        for mod in config["server_mods"]:
            lines.append("[[server_mods.mod]]")
            lines.append(f'name = "{mod["name"]}"')
            lines.append(f'url = "{mod["url"]}"')
            lines.append("")
    else:
        lines.append("# Example:")
        lines.append("# [[server_mods.mod]]")
        lines.append('# name = "lithium"')
        lines.append('# url = "https://cdn.modrinth.com/..."')
        lines.append("")

    return "\n".join(lines)


def generate_env_content(server_ip):
    """Generate .env file content."""
    lines = [
        "# Void-MC Environment Variables",
        "# This file contains sensitive configuration data",
        "# DO NOT COMMIT THIS FILE TO VERSION CONTROL",
        "",
        f"SERVER_IP={server_ip}",
        ""
    ]
    return "\n".join(lines)


def main():
    """Main setup function."""
    print_header("Void-MC Configuration Setup")
    print("\nThis wizard will help you configure your Minecraft server.")
    print("Your settings will be saved to config.toml")
    print("Server IP will be saved to .env (not committed to git)")

    # Load existing YAML data if available
    client_mods, server_mods, default_mc_version, default_fabric_loader = load_existing_yaml_mods()

    if client_mods or server_mods:
        print(f"\n✓ Found existing mod configurations:")
        if client_mods:
            print(f"  - {len(client_mods)} client mods")
        if server_mods:
            print(f"  - {len(server_mods)} server mods")
        print("  These will be migrated to the new config.toml")

    config = {}

    # Versions
    print_section("Version Configuration")
    config["minecraft_version"] = get_input("Minecraft version", default_mc_version)
    config["fabric_loader"] = get_input("Fabric loader version", default_fabric_loader)

    # Server IP (goes to .env)
    print_section("Network Configuration")
    print("Note: IP will be stored in .env file")
    server_ip = get_input("Server IP address", "0.0.0.0")
    server_port = get_input("Server port", "25565")

    # Server settings
    print_section("World Configuration")
    config["seed"] = get_input("World seed (leave empty for random)", "")

    print("\nDifficulty options: peaceful, easy, normal, hard")
    config["difficulty"] = get_input("Difficulty", "normal")

    print("\nGamemode options: survival, creative, adventure, spectator")
    config["gamemode"] = get_input("Default gamemode", "survival")

    print_section("Server Settings")
    config["max_players"] = int(get_input("Max players", "20"))
    config["view_distance"] = int(get_input("View distance (chunks)", "10"))
    config["spawn_protection"] = int(get_input("Spawn protection radius", "16"))

    config["pvp"] = get_yes_no("Enable PvP?", True)
    config["online_mode"] = get_yes_no("Enable online mode (authentication)?", True)

    config["motd"] = get_input("Server MOTD (Message of the Day)", "A Minecraft Server")

    # Add mods from YAML
    config["client_mods"] = client_mods
    config["server_mods"] = server_mods

    # Generate files
    print_section("Generating Configuration Files")

    # Generate config.toml
    config_path = Path("config.toml")
    toml_content = generate_toml_content(config)
    with open(config_path, 'w') as f:
        f.write(toml_content)
    print(f"✓ Created {config_path}")

    # Generate .env
    env_path = Path(".env")
    env_content = generate_env_content(f"{server_ip}:{server_port}")
    with open(env_path, 'w') as f:
        f.write(env_content)
    print(f"✓ Created {env_path}")

    # Summary
    print_header("Setup Complete!")
    print("\nNext steps:")
    print("  1. Review and edit config.toml as needed")
    print("  2. Run 'make generate-config' to create JSON configuration files")
    print("  3. Run 'make server-mods' or 'make client-mods' to download mods")
    print("  4. Run 'make run-server' to start the server")
    print("\nNote: The .env file has been created and added to .gitignore")
    print("      Do not commit sensitive data to version control!")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\n\nError: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
